/// Flutter icons PipelionAssetBox
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PipelionAssetBox
///      fonts:
///       - asset: fonts/PipelionAssetBox.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PipelionAssetBox {
  PipelionAssetBox._();

  static const _kFontFam = 'PipelionAssetBox';

  static const IconData box = const IconData(0xe800, fontFamily: _kFontFam);
}
